#!/bin/sh

set -e

# Initialise database
/usr/sbin/rt-setup-database --action init --skip-create

# Initialise database for repeatticket extension
cd /usr/src/rt-extension-repeatticket
/usr/sbin/rt-setup-database \
  --action insert \
  --datadir etc \
  --datafile etc/initialdata \
  --skip-create \
  --package RT::Extension::RepeatTicket
cd -
